dist: trusty
language: cpp
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
  # CLONE GTEST
  - git clone https://github.com/google/googletest.git
  # BUILD ZZ-CCI
  - mkdir build
  - cd build
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake  -DCMAKE_BUILD_TYPE=Release ../
  - make -j8
  # RUN UNIT TESTS
  - ./cciUT
