dist: trusty
language: cpp
compiler:
  - clang
  - gcc
script:
  # CLONE GTEST
  - git clone https://github.com/google/googletest.git
  # BUILD ZZ-CCI
  - mkdir build
  - cd build
  - cmake  -DCMAKE_BUILD_TYPE=Release ../
  - make -j8
  # RUN UNIT TESTS
  - ./cciUT
